# **REQUIRED MODULES**

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn import metrics
from statsmodels.iolib.smpickle import load_pickle
from google.colab import files

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
uploaded = files.upload()

Saving ols_results_delhi.pickle to ols_results_delhi.pickle


# **LOAD PICKLED MODEL**

In [3]:
new_results = load_pickle('ols_results_delhi.pickle')

In [4]:
print(new_results.summary())

                                 OLS Regression Results                                
Dep. Variable:                  Price   R-squared (uncentered):                   0.930
Model:                            OLS   Adj. R-squared (uncentered):              0.930
Method:                 Least Squares   F-statistic:                              6426.
Date:                Thu, 22 Oct 2020   Prob (F-statistic):                        0.00
Time:                        14:28:12   Log-Likelihood:                         -39289.
No. Observations:                2424   AIC:                                  7.859e+04
Df Residuals:                    2419   BIC:                                  7.862e+04
Df Model:                           5                                                  
Covariance Type:            nonrobust                                                  
                     coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------

# **SAMPLE INPUTS**

Arguments : Area, AttributeScore,	Resale,	LogPremium,	Bedrooms

In [6]:
# Area	AttributeScore	Resale	LogPremium	Bedrooms # expected price
new_results.predict([1050, 22, 1, 1.273397, 1])
# Expected Output: 11500000

array([14143229.2187847])

In [7]:
new_results.predict([720, 0, 1, 0.574353, 3])
# Expected Output: 3500000

array([3022309.7691475])

In [8]:
new_results.predict([800, 0, 1, 0.179333, 2])
# Expected Output: 2889000

array([3313030.80458358])